# Generated by Django 5.2.5 on 2025-08-25 12:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text="User's first name", max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, help_text="User's last name", max_length=30, verbose_name='Last Name')),
                ('phone', models.CharField(blank=True, help_text='Phone number in international format (e.g., +1234567890)', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('birth_date', models.DateField(blank=True, help_text="User's date of birth", null=True, verbose_name='Birth Date')),
                ('bio', models.TextField(blank=True, help_text='Short biography or description (max 500 characters)', max_length=500, verbose_name='Biography')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the profile was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the profile was last updated', verbose_name='Updated At')),
                ('user', models.OneToOneField(help_text='Associated user account for this profile', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'profiles_profile',
                'ordering': ['-created_at'],
            },
        ),
    ]
