# Generated by Django 5.2.5 on 2025-08-26 01:25

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for the account (e.g., "Chase Checking", "Emergency Fund")', max_length=100)),
                ('account_type', models.CharField(choices=[('checking', 'Checking Account'), ('savings', 'Savings Account'), ('credit_card', 'Credit Card'), ('investment', 'Investment Account'), ('cash', 'Cash')], help_text='Type of account for categorization and reporting', max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current account balance', max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('BRL', 'Brazilian Real'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar')], default='USD', help_text='Account currency code (ISO 4217)', max_length=3)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this account is currently active and should be included in calculations')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this account was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this account was last modified')),
                ('user', models.ForeignKey(help_text='Owner of this account', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='accounts_ac_user_id_0bca0f_idx'), models.Index(fields=['user', 'account_type'], name='accounts_ac_user_id_79e366_idx'), models.Index(fields=['created_at'], name='accounts_ac_created_25027f_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='unique_account_name_per_user')],
            },
        ),
    ]
