# Generated by Django 5.2.5 on 2025-08-26 13:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['name'], 'verbose_name': 'Conta', 'verbose_name_plural': 'Contas'},
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('checking', 'Conta Corrente'), ('savings', 'Conta Poupança'), ('credit_card', 'Cartão de Crédito'), ('investment', 'Conta de Investimento'), ('cash', 'Dinheiro')], help_text='Tipo de conta para categorização e relatórios', max_length=20, verbose_name='Tipo de Conta'),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saldo atual da conta', max_digits=12, verbose_name='Saldo'),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Quando esta conta foi criada', verbose_name='Criada em'),
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('USD', 'Dólar Americano'), ('EUR', 'Euro'), ('BRL', 'Real Brasileiro'), ('GBP', 'Libra Esterlina'), ('CAD', 'Dólar Canadense')], default='BRL', help_text='Código da moeda da conta (ISO 4217)', max_length=3, verbose_name='Moeda'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Se esta conta está ativa e deve ser incluída nos cálculos', verbose_name='Ativa'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(help_text='Nome descritivo para a conta (ex.: "Conta Corrente Itaú", "Fundo de Emergência")', max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Quando esta conta foi modificada pela última vez', verbose_name='Atualizada em'),
        ),
    ]
