# Generated by Django 5.2.5 on 2025-08-26 13:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_account_options_alter_account_account_type_and_more'),
        ('categories', '0002_alter_category_options_alter_category_category_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Receita'), ('EXPENSE', 'Despesa')], help_text='Se esta transação é uma receita ou despesa', max_length=10, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Valor da transação (sempre positivo)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('description', models.CharField(help_text='Descrição breve da transação', max_length=200, verbose_name='Descrição')),
                ('transaction_date', models.DateField(help_text='Data em que a transação foi realizada', verbose_name='Data da Transação')),
                ('notes', models.TextField(blank=True, help_text='Observações adicionais sobre a transação (opcional)', null=True, verbose_name='Observações')),
                ('is_recurring', models.BooleanField(default=False, help_text='Se esta transação se repete automaticamente', verbose_name='Recorrente')),
                ('recurrence_type', models.CharField(blank=True, choices=[('DAILY', 'Diária'), ('WEEKLY', 'Semanal'), ('BIWEEKLY', 'Quinzenal'), ('MONTHLY', 'Mensal'), ('QUARTERLY', 'Trimestral'), ('SEMIANNUAL', 'Semestral'), ('ANNUAL', 'Anual')], help_text='Frequência de repetição (apenas para transações recorrentes)', max_length=15, null=True, verbose_name='Tipo de Recorrência')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Quando esta transação foi registrada no sistema', verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Quando esta transação foi modificada pela última vez', verbose_name='Atualizada em')),
                ('account', models.ForeignKey(help_text='Conta bancária ou cartão onde a transação foi realizada', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.account', verbose_name='Conta')),
                ('category', models.ForeignKey(help_text='Categoria para organização e relatórios', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='categories.category', verbose_name='Categoria')),
                ('user', models.ForeignKey(help_text='Owner of this transaction', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'transaction_date'], name='transaction_user_id_e55ebe_idx'), models.Index(fields=['user', 'account'], name='transaction_user_id_295b1e_idx'), models.Index(fields=['user', 'category'], name='transaction_user_id_cb8cb9_idx'), models.Index(fields=['user', 'transaction_type'], name='transaction_user_id_98a6b3_idx'), models.Index(fields=['transaction_date', 'transaction_type'], name='transaction_transac_262c72_idx'), models.Index(fields=['account', 'transaction_date'], name='transaction_account_201187_idx'), models.Index(fields=['category', 'transaction_date'], name='transaction_categor_99d969_idx'), models.Index(fields=['is_recurring'], name='transaction_is_recu_a1023e_idx'), models.Index(fields=['created_at'], name='transaction_created_67ce7b_idx')],
            },
        ),
    ]
