# Generated by Django 5.2.5 on 2025-08-26 01:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., "Food", "Transportation", "Salary")', max_length=50)),
                ('category_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], help_text='Whether this category is for income or expenses', max_length=10)),
                ('color', models.CharField(choices=[('#10B981', 'Green'), ('#3B82F6', 'Blue'), ('#8B5CF6', 'Purple'), ('#F59E0B', 'Yellow'), ('#EF4444', 'Red'), ('#06B6D4', 'Cyan'), ('#84CC16', 'Lime'), ('#F97316', 'Orange'), ('#EC4899', 'Pink'), ('#6B7280', 'Gray')], default='#6B7280', help_text='Hex color code for visual identification in UI', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid hex color code (e.g., #10B981)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('icon', models.CharField(choices=[('💰', 'Money Bag'), ('💳', 'Credit Card'), ('🏠', 'House'), ('🚗', 'Car'), ('🍔', 'Food'), ('⚡', 'Utilities'), ('🎬', 'Entertainment'), ('👔', 'Work'), ('🏥', 'Healthcare'), ('🎓', 'Education'), ('✈️', 'Travel'), ('🛍️', 'Shopping'), ('💊', 'Pharmacy'), ('⛽', 'Gas'), ('📱', 'Technology'), ('🎁', 'Gifts'), ('🏃', 'Sports'), ('📊', 'Investment'), ('🔧', 'Maintenance'), ('📚', 'Books')], default='💰', help_text='Emoji icon for visual identification', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is active and available for use')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this category was created')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category for hierarchical organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categories.category')),
                ('user', models.ForeignKey(help_text='Owner of this category', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['category_type', 'name'],
                'indexes': [models.Index(fields=['user', 'category_type', 'is_active'], name='categories__user_id_3bd7a3_idx'), models.Index(fields=['user', 'parent'], name='categories__user_id_419e65_idx'), models.Index(fields=['category_type', 'is_active'], name='categories__categor_96b276_idx'), models.Index(fields=['created_at'], name='categories__created_6b010e_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'name', 'category_type'), name='unique_category_name_per_user_type')],
            },
        ),
    ]
