# Generated by Django 5.2.5 on 2025-08-26 13:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_type', 'name'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('INCOME', 'Receita'), ('EXPENSE', 'Despesa')], help_text='Se esta categoria é para receitas ou despesas', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('#10B981', 'Verde'), ('#3B82F6', 'Azul'), ('#8B5CF6', 'Roxo'), ('#F59E0B', 'Amarelo'), ('#EF4444', 'Vermelho'), ('#06B6D4', 'Ciano'), ('#84CC16', 'Lima'), ('#F97316', 'Laranja'), ('#EC4899', 'Rosa'), ('#6B7280', 'Cinza')], default='#6B7280', help_text='Código hexadecimal da cor para identificação visual', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid hex color code (e.g., #10B981)', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Quando esta categoria foi criada', verbose_name='Criada em'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('💰', 'Saco de Dinheiro'), ('💳', 'Cartão de Crédito'), ('🏠', 'Casa'), ('🚗', 'Carro'), ('🍔', 'Comida'), ('⚡', 'Utilidades'), ('🎬', 'Entretenimento'), ('👔', 'Trabalho'), ('🏥', 'Saúde'), ('🎓', 'Educação'), ('✈️', 'Viagem'), ('🛍️', 'Compras'), ('💊', 'Farmácia'), ('⛽', 'Combustível'), ('📱', 'Tecnologia'), ('🎁', 'Presentes'), ('🏃', 'Esportes'), ('📊', 'Investimento'), ('🔧', 'Manutenção'), ('📚', 'Livros')], default='💰', help_text='Ícone emoji para identificação visual', max_length=10, verbose_name='Ícone'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Se esta categoria está ativa e disponível para uso', verbose_name='Ativa'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Nome da categoria (ex.: "Alimentação", "Transporte", "Salário")', max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Categoria pai para organização hierárquica', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categories.category', verbose_name='Categoria Pai'),
        ),
    ]
