# Generated by Django 5.2.5 on 2025-08-27 11:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_alter_category_options_alter_category_category_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome descritivo do orçamento (ex.: "Alimentação Janeiro 2024")', max_length=100, verbose_name='Nome')),
                ('planned_amount', models.DecimalField(decimal_places=2, help_text='Valor total planejado para este orçamento', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Planejado')),
                ('start_date', models.DateField(help_text='Data de início do período do orçamento', verbose_name='Data de Início')),
                ('end_date', models.DateField(help_text='Data de fim do período do orçamento', verbose_name='Data de Fim')),
                ('is_active', models.BooleanField(default=True, help_text='Se este orçamento está ativo e sendo monitorado', verbose_name='Ativo')),
                ('_cached_spent_amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Cached spent amount for performance (auto-calculated)', max_digits=12, null=True)),
                ('_cache_updated_at', models.DateTimeField(blank=True, help_text='When the cached values were last updated', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Quando este orçamento foi criado', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Quando este orçamento foi modificado pela última vez', verbose_name='Atualizado em')),
                ('category', models.ForeignKey(help_text='Categoria para este orçamento', on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='categories.category', verbose_name='Categoria')),
                ('user', models.ForeignKey(help_text='Owner of this budget', on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ['-start_date', 'name'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='budgets_bud_user_id_cec771_idx'), models.Index(fields=['user', 'category'], name='budgets_bud_user_id_72baec_idx'), models.Index(fields=['user', 'start_date', 'end_date'], name='budgets_bud_user_id_ea9bf3_idx'), models.Index(fields=['category', 'start_date', 'end_date'], name='budgets_bud_categor_009827_idx'), models.Index(fields=['start_date', 'end_date', 'is_active'], name='budgets_bud_start_d_b9ab95_idx'), models.Index(fields=['created_at'], name='budgets_bud_created_42c3b2_idx'), models.Index(fields=['_cache_updated_at'], name='budgets_bud__cache__e92950_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'category', 'start_date'), name='unique_budget_per_user_category_period'), models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='budget_end_date_after_start_date'), models.CheckConstraint(condition=models.Q(('planned_amount__gt', 0)), name='budget_positive_planned_amount')],
            },
        ),
    ]
